version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ../apps/greenpress/db-data:/data/db
  redis:
    image: redis
  admin:
    image: greenpress/admin-panel:${ADMIN_PANEL_VERSION}
  front:
    image: greenpress/front-ssr:${FRONT_SSR_VERSION}
    environment:
      GATEWAY_SERVICE_URL: gateway
  assets:
    image: greenpress/assets:${ASSETS_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${ASSETS_MONGODB_URI}
      REDIS_URL: redis://redis
      SECRETS_SERVICE_URL: secrets
      AUTH_SERVICE_URL: auth
      SECRETS_TOKEN: ${ASSETS_SECRETS_TOKEN}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      IP: 0.0.0.0
    depends_on:
      - mongo
      - redis
  auth:
    image: greenpress/auth:${AUTH_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${AUTH_MONGODB_URI}
      IP: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      APPLICATION_URL: ${APPLICATION_URL}
    depends_on:
      - mongo
  gateway:
    image: greenpress/gateway:${GATEWAY_VERSION}
    ports:
      - ${PORT}:3000
    environment:
      IP: 0.0.0.0
      TENANT: ${TENANT}
      APPLICATION_URL: ${APPLICATION_URL}
      CONTENT_SERVICE_URL: content
      AUTH_SERVICE_URL: auth
      ASSETS_SERVICE_URL: assets
      ADMIN_PANEL_URL: admin
      FRONT_URL: front
  content:
    image: greenpress/content:${CONTENT_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${CONTENT_MONGODB_URI}
      REDIS_URL: redis://redis
      IP: 0.0.0.0
      AUTH_SERVICE_URL: auth
    depends_on:
      - mongo
      - redis
  secrets:
    image: greenpress/secrets:${SECRETS_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${SECRETS_MONGODB_URI}
      IP: 0.0.0.0
      SECRET: ${SECRETS_SERVICE_SECRET}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    depends_on:
      - mongo
  drafts:
    image: greenpress/drafts:${DRAFTS_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${DRAFTS_MONGODB_URI}
      IP: 0.0.0.0
    depends_on:
      - mongo

networks:
  common_network:
