apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-config
data:
    BASIC_TENANT: ${TENANT}
    APPLICATION_URL: "{{ .Values.APPLICATION_URL }}"
    INTERNAL_URL: "{{ .Release.Name }}-gateway"
    CONTENT_SERVICE_URL: "{{ .Release.Name }}-content"
    AUTH_SERVICE_URL: "{{ .Release.Name }}-auth"
    DRAFTS_SERVICE_URL: "{{ .Release.Name }}-drafts"
    ASSETS_SERVICE_URL: "{{ .Release.Name }}-assets"
    ADMIN_PANEL_URL: "{{ .Release.Name }}-admin"
    IP: "0.0.0.0"
